In [1]:
import pandas as pd

In [2]:
data = "../data/feed-views.log"

## **Датафрейм views**

In [3]:
views = pd.read_csv(data, names=["datetime", "user"], sep="\t")

views["datetime"] = pd.to_datetime(views["datetime"])
views["year"] = views["datetime"].dt.year
views["month"] = views["datetime"].dt.month
views["day"] = views["datetime"].dt.day
views["hour"] = views["datetime"].dt.hour
views["minute"] = views["datetime"].dt.minute
views["second"] = views["datetime"].dt.second

## **Столбец daytime**

In [4]:
bins = [0, 4, 7, 11, 17, 20, 24]
labels = ["night", "early morning", "morning", "afternoon", "early evening", "evening"]
views["daytime"] = pd.cut(views["hour"], bins=bins, labels=labels, right=False)

views = views.set_index("user")

## **Подсчет элементов в датафрейме**

In [5]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [6]:
views.value_counts("daytime")

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

## **Сортировка значений в датафрейме одновременно по часам, минутам и секундам по возрастанию**

In [7]:
views.sort_values(["hour", "minute", "second"])

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...
artem,2020-05-21 23:49:22.386789,2020,5,21,23,49,22,evening
anatoliy,2020-05-09 23:53:55.599821,2020,5,9,23,53,55,evening
pavel,2020-05-09 23:54:54.260791,2020,5,9,23,54,54,evening
valentina,2020-05-14 23:58:56.754866,2020,5,14,23,58,56,evening
alexander,2020-05-14 23:59:38.758438,2020,5,14,23,59,38,evening

## **Минимум и максимум для часов и мода для категорий daytime**

## **Максимальный час для строк, где время суток - night**

In [8]:
max = views[views["daytime"] == "night"]["hour"].max()

## **Минимальный час для строк, где время суток - morning**

In [9]:
min = views[views["daytime"] == "morning"]["hour"].min()

## **Пользователи, которые посещали страницу в найденные часы**

In [10]:
views[views["hour"] == max].head(1)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night

In [11]:
views[views["hour"] == min].head(1)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning

## **Mода для часа и для daytime**

In [12]:
views["hour"].mode()

0    22
Name: hour, dtype: int32

In [13]:
views["daytime"].mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

## **Три самых ранних и три самых поздних часа дня и соответствующие имена пользователей**

In [14]:
views.nsmallest(3, "hour")

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
artem,2020-04-18 00:30:45.051569,2020,4,18,0,30,45,night
konstantin,2020-04-19 00:17:22.720860,2020,4,19,0,17,22,night
konstantin,2020-04-19 00:17:28.624573,2020,4,19,0,17,28,night

In [15]:
views.nlargest(3, "hour")

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-18 23:06:34.198911,2020,4,18,23,6,34,evening
artem,2020-04-18 23:40:32.666884,2020,4,18,23,40,32,evening
artem,2020-04-19 23:10:03.761243,2020,4,19,23,10,3,evening

## **Базовая статистика по столбцам**

In [16]:
q3 = views["hour"].describe()["75%"]
q1 = views["hour"].describe()["25%"]
iqr = q3 - q1
print(iqr)

9.0

In [17]:
views.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1076 entries, artem to artem
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1076 non-null   datetime64[ns]
 1   year      1076 non-null   int32
 2   month     1076 non-null   int32
 3   day       1076 non-null   int32
 4   hour      1076 non-null   int32
 5   minute    1076 non-null   int32
 6   second    1076 non-null   int32
 7   daytime   1076 non-null   category
dtypes: category(1), datetime64[ns](1), int32(6)
memory usage: 75.6+ KB